server:
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.lessing.equipment.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      db-column-underline: true  # 驼峰下划线转换
      refresh-mapper: true
      logic-delete-value: 1  # 逻辑删除配置
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

spring:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接 池中的最小空闲连接     shanghaiyidian  47.97.217.26    124.221.255.113
  datasource:
    url: jdbc:mysql://47.97.217.26:3306/dmdata?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: shanghaiyidian
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5

openapi:
  #获取token的地址
  rympurl: http://localhost:8082/camera/cameras
  closeurl: http://localhost:8082/camera/close
#  tpurl: 192.168.2.26:8080/
  local: C:\Users\Administrator\Desktop\nginx-1.23.1\img
  zpurl: https://camera.inesa-yszlkj.com/imgs/


#token:
#  time: 1800

